### ISSUE TITLE
Version 20180504 - chapter 10: Create a band fails

### ISSUE THREAD

**Issue by belgoros** [balinterdi/rarwe-issues#318]
I can't figure out why the test fails:
```
Acceptance | Bands: Create a band
    ✘ Uncaught Error: Assertion Failed: You attempted to define a `{{link-to "bands.band.details"}}` but did not pass th
e parameters required for generating its dynamic segments. You must provide param `id` to `generate`.
```
The code in the template seems to be exactly the same as in the book:
```
# templates/bands/band.hbs

<nav class="rr-navbar" role="navigation">
  <ul class="rr-nav">
    <li class="rr-navbar-item" data-test-rr="details-nav-item">
    {{link-to "Details" "bands.band.details"}}
    </li>
    <li class="rr-navbar-item" data-test-rr="songs-nav-item">
      {{link-to "Songs" "bands.band.songs"}}
    </li>
  </ul> </nav>
{{outlet}}
```

<img width="1203" alt="screen shot 2018-05-15 at 12 00 59" src="https://user-images.githubusercontent.com/83579/40050417-afd2e3d4-5837-11e8-8e4d-5197c9bda6af.png">

If I call `link-to`helper and pass in the model id:
```
# templates/bands/band.hbs

<nav class="rr-navbar" role="navigation">
  <ul class="rr-nav">
    <li class="rr-navbar-item" data-test-rr="details-nav-item">
    {{link-to "Details" "bands.band.details" model.id}}
    </li>
    <li class="rr-navbar-item" data-test-rr="songs-nav-item">
      {{link-to "Songs" "bands.band.songs" model.id}}
    </li>
  </ul> </nav>
{{outlet}}
```
 it goes better but the last test still fails:
```
Acceptance | Bands: Create a band
    ✘ Element [data-test-rr=songs-nav-item] > .active exists
            at DOMAssertions.findTargetElement (http://localhost:7357/assets/test-support.js:8998:16)
            at DOMAssertions.hasText (http://localhost:7357/assets/test-support.js:8719:26)
            at Object.<anonymous> (http://localhost:7357/assets/tests.js:28:61)
'Error while processing route: bands.band.songs' 'Assertion Failed: Cannot call get with \'id\' on an undefined object.'
 'Error: Assertion Failed: Cannot call get with \'id\' on an undefined object.\n    at new EmberError (http://localhost:
```

Thank you

**Comment by belgoros** [comment]
My bad, I found the reason of the error, - I still had a place where I calles `slug`on a newly created band:
```javascript
#controllers/bands.js

async saveBand(event) {
      event.preventDefault();
      let newBand = this.store.createRecord('band', { name: this.newBandName });
      await newBand.save();
      this.setProperties({
        newBandName: '',
        isAddingBand: false
      });
      this.transitionToRoute('bands.band.songs', newBand.slug);
    }
```
After changing the line `this.transitionToRoute('bands.band.songs', newBand.slug);` to `this.transitionToRoute('bands.band.songs', newBand.id);` all the tests came back to green. Thank you.
