### ISSUE TITLE
Trouble getting the test suite to pass

### ISSUE THREAD

**Issue by Jordan4jc** [balinterdi/rarwe-issues#83]
I just finished adding the mock http test helpers and when trying to convert them over I am having an issue getting the suite to pass all of a sudden and I can't seem to make out what the error is and how to fix it. It is specifically at the adding a song part, which the book does not show how to convert to use the new helper.

Here is the `// tests/acceptance/bands-test.js` content I have right now

```
import Ember from 'ember';
import { module, test } from 'qunit';
import startApp from 'rarwe/tests/helpers/start-app';
import Pretender from 'pretender';
import httpStubs from '../helpers/http-stubs';

var application, 
    server;

module('Acceptance | bands', {
  beforeEach: function() {
    application = startApp();
  },

  afterEach: function() {
    Ember.run(application, 'destroy');
    server.shutdown();
  }
});

test('List bands', function(assert) {
  server = new Pretender(function(){
    httpStubs.stubBands(this, {
      bands: [
        { id: 1, name: 'Radiohead' },
        { id: 2, name: 'Long Distance Calling'}
      ]
    });
  });

  visit('/bands');

  andThen(function() {
    assertLength(assert,'.band-link',2,"All band links are rendered");
    assertLength(assert,'.band-link:contains("Radiohead")',1,"First band link contains the band name");
    assertLength(assert,'.band-link:contains("Long Distance Calling")',1,"The other band link contains the band name");
  });
});

test('Create a new band', function(assert){
  server = new Pretender(function(){
    httpStubs.stubBands(this, {
      bands: [
        { id: 1, name: 'Radiohead' }
      ]
    });
    httpStubs.stubCreateBand(this);
  });

  visit('/bands');

  fillIn('.new-band','Long Distance Calling');
  click('.new-band-button');

  andThen(function(){
    assertLength(assert,'.band-link',2,"All band links are rendered");
    assertTrimmedText(assert, '.band-link:last', 'Long Distance Calling', "Created band appears at the end of the list");
    assertElement(assert, '.nav a.active:contains("Songs")', "The Songs tab is active");
  });
});

test('Create a new song in two steps', function(assert){
  server = new Pretender(function(){
    httpStubs.stubBands(this, {
      bands: [
        { id: 1, name: 'Radiohead' }
      ]
    });
    httpStubs.stubCreateBand(this);
    httpStubs.stubCreateBand(this,{
      song: {
        id: 1,
        title: 'Killer Cars'
      }
    });
  });

  visit('/');

  selectBand('Radiohead');
  click('a:contains("create one")');
  fillIn('.new-song', 'Killer Cars');
  submit('.new-song-form');

  andThen(function() {
    assertLength(assert,'.songs .song:contains("Killer Cars")',1,"Creates the song and displays it in the list");
  });
});
```

And the failing test says this

```
Acceptance | bands: Create a new song in two steps (1, 0, 1)Rerun615 ms
Creates the song and displays it in the list@ 555 ms
Expected: 	
1
Result: 	
0
Diff: 	
10
Source: 	
    at assertLength (http://localhost:4200/assets/rarwe.js:1585:10)
    at http://localhost:4200/assets/vendor.js:53059:19
    at http://localhost:4200/assets/rarwe.js:1489:7
    at andThen (http://localhost:4200/assets/vendor.js:52386:33)
    at http://localhost:4200/assets/vendor.js:53072:19
    at isolate (http://localhost:4200/assets/vendor.js:53273:13)
```

**Comment by balinterdi** [comment]
> It is specifically at the adding a song part, which the book does not show how to convert to use the new helper.

If you tell me exactly which part this is (by mentioning the page number), I'll copy-paste the snippet here and that might make your test pass.

You can also insert `return pauseTest();` at the point in the test where you'd like to freeze it and then you can see the application under test in the little iframe which might give you a hint.

Hope that helps.

**Comment by Jordan4jc** [comment]
Using `return pauseTest();` I was able to figure out the issue by stepping through each part. Thanks for that tip.

**Comment by balinterdi** [comment]
I'm glad it worked, `pauseTest` should probably be in the book, btw ;)
